name: Handle issues
on: issues
jobs:
    check:
        name: output-info
        runs-on: ubuntu-latest
        steps:
            - name: output event details
              run: echo "${{ toJson(github.event) }}"